
import type { TimetableData } from "@/app/timetable/page";

const btechCse1A_Timetable: TimetableData = {
    course: 'B.Tech',
    program: 'CSE',
    semester: '1',
    section: 'A',
    schedule: {
        Monday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Programming for Problem Solving', subjectCode: 'CSE 104', facultyName: 'Dr. C.S. Raghuvans', facultyCode: 'CSR' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'Basic Mechanical Engineering', subjectCode: 'BME 101', facultyName: 'Dr. Anshul Gangele', facultyCode: 'ASL' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Environmental Studies - I', subjectCode: 'EVS 142', facultyName: 'Dr. Rwitrabrata M', facultyCode: 'RWM' },
            { id: 'LUNCH', fromTime: '12:15', toTime: '13:10' },
            { id: 'L4', fromTime: '13:15', toTime: '14:10', subjectName: 'French - I', subjectCode: 'FLU 144', facultyName: 'Mr. K. Muthuvel', facultyCode: 'KMU' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'Communication Skills - I', subjectCode: 'BCU 141', facultyName: 'Dr. Monika Saxeni', facultyCode: 'MKS' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'Applied Physics - I', subjectCode: 'PHY 101', facultyName: 'Dr. Nirbhay Singh', facultyCode: 'NBS' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'LIBRARY/CCA', subjectCode: '', facultyName: '', facultyCode: '' },
        ],
        Tuesday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Applied Mathematics - I', subjectCode: 'MAT 101', facultyName: 'Dr. Santosh Kr Sharma', facultyCode: 'SNT' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'Applied Physics - I', subjectCode: 'PHY 101', facultyName: 'Dr. Nirbhay Singh', facultyCode: 'NBS' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'LIBRARY/CCA', subjectCode: '', facultyName: '', facultyCode: '' },
            { id: 'LUNCH', fromTime: '12:15', toTime: '13:10' },
            { id: 'L4', fromTime: '13:15', toTime: '14:10', subjectName: 'Basic Civil Engineering & Applied Mechanics', subjectCode: 'CIV 101', facultyName: 'Dr. P. Mahakavi', facultyCode: 'PMK' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'Communication Skills - I', subjectCode: 'BCU 141', facultyName: 'Dr. Monika Saxeni', facultyCode: 'MKS' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'LIBRARY/CCA', subjectCode: '', facultyName: '', facultyCode: '' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'Applied Physics Lab - I', subjectCode: 'PHY 121', facultyName: 'Dr. Nirbhay Singh', facultyCode: 'NBS' },
        ],
        Wednesday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Programming for Problem Solving', subjectCode: 'CSE 104', facultyName: 'Dr. C.S. Raghuvans', facultyCode: 'CSR' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'Workshop/Manufacturing Practices Lab', subjectCode: 'BME 124', facultyName: 'Dr. Susheel Pandey', facultyCode: 'SHP' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Programming for Problem Solving Lab', subjectCode: 'CSE 124', facultyName: 'Dr. C.S. Raghuvans', facultyCode: 'CSR' },
            { id: 'LUNCH', fromTime: '12:15', toTime: '13:10' },
            { id: 'L4', fromTime: '13:15', toTime: '14:10', subjectName: 'Environmental Studies - I', subjectCode: 'EVS 142', facultyName: 'Dr. Rwitrabrata M', facultyCode: 'RWM' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'Applied Mathematics - I', subjectCode: 'MAT 101', facultyName: 'Dr. Santosh Kr Sharma', facultyCode: 'SNT' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'Basic Mechanical Engineering', subjectCode: 'BME 101', facultyName: 'Dr. Anshul Gangele', facultyCode: 'ASL' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'LIBRARY/CCA', subjectCode: '', facultyName: '', facultyCode: '' },
        ],
        Thursday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Applied Physics - I', subjectCode: 'PHY 101', facultyName: 'Dr. Nirbhay Singh', facultyCode: 'NBS' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'Programming for Problem Solving', subjectCode: 'CSE 104', facultyName: 'Dr. C.S. Raghuvans', facultyCode: 'CSR' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Behavioural Science - I', subjectCode: 'BSU 143', facultyName: 'Dr. Yukti', facultyCode: 'YKT' },
            { id: 'LUNCH', fromTime: '12:15', toTime: '13:10' },
            { id: 'L4', fromTime: '13:15', toTime: '14:10', subjectName: 'Programming for Problem Solving Lab', subjectCode: 'CSE 124', facultyName: 'Dr. C.S. Raghuvans', facultyCode: 'CSR' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'Workshop/Manufacturing Practices Lab', subjectCode: 'BME 124', facultyName: 'Dr. Susheel Pandey', facultyCode: 'SHP' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'Applied Mathematics - I', subjectCode: 'MAT 101', facultyName: 'Dr. Santosh Kr Sharma', facultyCode: 'SNT' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: '', subjectCode: '', facultyName: '', facultyCode: '' },
        ],
        Friday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Applied Physics - I', subjectCode: 'PHY 101', facultyName: 'Dr. Nirbhay Singh', facultyCode: 'NBS' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'Applied Physics Lab - I', subjectCode: 'PHY 121', facultyName: 'Dr. Nirbhay Singh', facultyCode: 'NBS' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'LIBRARY/CCA', subjectCode: '', facultyName: '', facultyCode: '' },
            { id: 'LUNCH', fromTime: '12:15', toTime: '13:10' },
            { id: 'L4', fromTime: '13:15', toTime: '14:10', subjectName: 'Applied Mathematics - I', subjectCode: 'MAT 101', facultyName: 'Dr. Santosh Kr Sharma', facultyCode: 'SNT' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'Basic Mechanical Engineering', subjectCode: 'BME 101', facultyName: 'Dr. Anshul Gangele', facultyCode: 'ASL' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'LIBRARY/CCA', subjectCode: '', facultyName: '', facultyCode: '' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'LIBRARY/CCA', subjectCode: '', facultyName: '', facultyCode: '' },
        ],
        Saturday: [],
        Sunday: [],
    },
};
const btechCse1B_Timetable: TimetableData = {
    course: 'B.Tech',
    program: 'CSE',
    semester: '1',
    section: 'B',
    schedule: {
        Monday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Applied Physics - I', subjectCode: 'PHY 101', facultyName: 'Ms. Apoorva Sharma', facultyCode: 'APS' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'PPS LAB (Group 1) / AP LAB - I (Group 2)', subjectCode: 'CSE 124 / PHY 121', facultyName: 'Dr. C.S. Raghuvanshi / Dr. Manisha Singh', facultyCode: 'CSR / MNS' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Basic Mechanical Engineering', subjectCode: 'BME 101', facultyName: 'Ms. Apoorva Sharma', facultyCode: 'ASP' },
            { id: 'LUNCH', fromTime: '12:15', toTime: '13:10' },
            { id: 'L4', fromTime: '13:15', toTime: '14:10', subjectName: 'Environmental Studies - I', subjectCode: 'EVS 142', facultyName: 'Dr. Nidhi Shukla', facultyCode: 'NDS' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'Applied Mathematics - I', subjectCode: 'MAT 101', facultyName: 'Dr. Santosh Kr Sharm', facultyCode: 'SNT' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'Communication Skills - I', subjectCode: 'BCU 141', facultyName: 'Dr. Monika Saxena', facultyCode: 'MKS' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'Programming for Problem Solving', subjectCode: 'CSE 104', facultyName: 'Dr. C.S. Raghuvanshi', facultyCode: 'CSR' },
        ],
        Tuesday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Basic Civil Eng. & Applied Mechanics', subjectCode: 'CIV 101', facultyName: 'Mr. Sachin Tiwari', facultyCode: 'SCH' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'AP LAB - I (Group 1) / LIBRARY/CCA (Group 2)', subjectCode: 'PHY 121', facultyName: 'Dr. Manisha Singh', facultyCode: 'MNS' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Applied Physics - I', subjectCode: 'PHY 101', facultyName: 'Dr. Pankaj Mishra', facultyCode: 'PKM' },
            { id: 'LUNCH', fromTime: '12:15', toTime: '13:10' },
            { id: 'L4', fromTime: '13:15', toTime: '14:10', subjectName: 'Basic Mechanical Engineering', subjectCode: 'BME 101', facultyName: 'Ms. Apoorva Sharma', facultyCode: 'ASP' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'French - I', subjectCode: 'FLU 144', facultyName: 'Dr. Neelam Singh Ton', facultyCode: 'NLT' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'Communication Skills - I', subjectCode: 'BCU 141', facultyName: 'Dr. Monika Saxena', facultyCode: 'MKS' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'Applied Physics - I', subjectCode: 'PHY 101', facultyName: 'Dr. Pankaj Mishra', facultyCode: 'PKM' },
        ],
        Wednesday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Applied Mathematics - I', subjectCode: 'MAT 101', facultyName: 'Dr. Santosh Kr Sharm', facultyCode: 'SNT' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'LIBRARY/CCA', subjectCode: '', facultyName: '', facultyCode: '' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Applied Physics - I', subjectCode: 'PHY 101', facultyName: 'Dr. Pankaj Mishra', facultyCode: 'PKM' },
            { id: 'LUNCH', fromTime: '12:15', toTime: '13:10' },
            { id: 'L4', fromTime: '13:15', toTime: '14:10', subjectName: 'WP LAB (Group 1) / PPS LAB (Group 2)', subjectCode: 'BME 124 / CSE 124', facultyName: 'Ms. Apoorva Sharma / Dr. C.S. Raghuvanshi', facultyCode: 'ASP / CSR' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'LIBRARY/CCA', subjectCode: '', facultyName: '', facultyCode: '' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'LIBRARY/CCA', subjectCode: '', facultyName: '', facultyCode: '' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'LIBRARY/CCA', subjectCode: '', facultyName: '', facultyCode: '' },
        ],
        Thursday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Programming for Problem Solving', subjectCode: 'CSE 104', facultyName: 'Dr. C.S. Raghuvanshi', facultyCode: 'CSR' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'Applied Mathematics - I', subjectCode: 'MAT 101', facultyName: 'Dr. Santosh Kr Sharm', facultyCode: 'SNT' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Behavioural Science - I', subjectCode: 'BSU 143', facultyName: 'Dr Shubhagata Awasti', facultyCode: 'SBA' },
            { id: 'LUNCH', fromTime: '12:15', toTime: '13:10' },
            { id: 'L4', fromTime: '13:15', toTime: '14:10', subjectName: 'LIBRARY/CCA', subjectCode: '', facultyName: '', facultyCode: '' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'Applied Physics - I', subjectCode: 'PHY 101', facultyName: 'Dr. Pankaj Mishra', facultyCode: 'PKM' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'Environmental Studies - I', subjectCode: 'EVS 142', facultyName: 'Dr. Nidhi Shukla', facultyCode: 'NDS' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'LIBRARY/CCA', subjectCode: '', facultyName: '', facultyCode: '' },
        ],
        Friday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Programming for Problem Solving', subjectCode: 'CSE 104', facultyName: 'Dr. C.S. Raghuvanshi', facultyCode: 'CSR' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'Applied Mathematics - I', subjectCode: 'MAT 101', facultyName: 'Dr. Santosh Kr Sharm', facultyCode: 'SNT' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Basic Civil Eng. & Applied Mechanics', subjectCode: 'CIV 101', facultyName: 'Mr. Sachin Tiwari', facultyCode: 'SCH' },
            { id: 'LUNCH', fromTime: '12:15', toTime: '13:10' },
            { id: 'L4', fromTime: '13:15', toTime: '14:10', subjectName: 'Basic Mechanical Engineering', subjectCode: 'BME 101', facultyName: 'Ms. Apoorva Sharma', facultyCode: 'ASP' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'LIBRARY/CCA (Group 1) / WP LAB (Group 2)', subjectCode: 'BME 124', facultyName: 'Ms. Apoorva Sharma', facultyCode: 'ASP' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'LIBRARY/CCA', subjectCode: '', facultyName: '', facultyCode: '' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'LIBRARY/CCA', subjectCode: '', facultyName: '', facultyCode: '' },
        ],
        Saturday: [],
        Sunday: [],
    }
};
  
const btechCse1C_Timetable: TimetableData = {
    course: 'B.Tech',
    program: 'CSE',
    semester: '1',
    section: 'C',
    schedule: {
        Monday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'PPS LAB (Group 1) / WP LAB (Group 2)', subjectCode: 'CSE 124 / BME 124', facultyName: 'Dr. Ganesh Gupta / Dr. Susheel Pandey', facultyCode: 'GGP / SHP' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'PPS LAB (Group 1) / WP LAB (Group 2)', subjectCode: 'CSE 124 / BME 124', facultyName: 'Dr. Ganesh Gupta / Dr. Susheel Pandey', facultyCode: 'GGP / SHP' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Applied Mathematics - I', subjectCode: 'MAT 101', facultyName: 'Dr. Alok Jain', facultyCode: 'ALK' },
            { id: 'LUNCH', fromTime: '12:15', toTime: '13:10' },
            { id: 'L4', fromTime: '13:15', toTime: '14:10', subjectName: 'Applied Physics - I', subjectCode: 'PHY 101', facultyName: 'Dr. Nirbhay Singh', facultyCode: 'NBS' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'Communication Skills - I', subjectCode: 'BCU 141', facultyName: 'Dr. Sonia Srivastav', facultyCode: 'SSV' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'LIBRARY/CCA', subjectCode: 'LIBRARY', facultyName: '', facultyCode: '' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'LIBRARY/CCA', subjectCode: 'LIBRARY', facultyName: '', facultyCode: '' },
        ],
        Tuesday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Applied Physics - I', subjectCode: 'PHY 101', facultyName: 'Dr. Nirbhay Singh', facultyCode: 'NBS' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'LIBRARY/CCA', subjectCode: 'LIBRARY', facultyName: '', facultyCode: '' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Basic Mechanical Engineering', subjectCode: 'BME 101', facultyName: 'Dr. Susheel Pandey', facultyCode: 'SHP' },
            { id: 'LUNCH', fromTime: '12:15', toTime: '13:10' },
            { id: 'L4', fromTime: '13:15', toTime: '14:10', subjectName: 'Environmental Studies - I', subjectCode: 'EVS 142', facultyName: 'Dr. Abhishek Kumar', facultyCode: 'ABB' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'Communication Skills - I', subjectCode: 'BCU 141', facultyName: 'Dr. Sonia Srivastav', facultyCode: 'SSV' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'Basic Civil Engineering & Applied Mechanics', subjectCode: 'CIV 101', facultyName: 'Dr. Imran Ahmad', facultyCode: 'IMN' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'Programming for Problem Solving', subjectCode: 'CSE 104', facultyName: 'Dr. Ganesh Gupta', facultyCode: 'GGP' },
        ],
        Wednesday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Programming for Problem Solving', subjectCode: 'CSE 104', facultyName: 'Dr. Ganesh Gupta', facultyCode: 'GGP' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'Applied Physics - I', subjectCode: 'PHY 101', facultyName: 'Dr. Nirbhay Singh', facultyCode: 'NBS' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Applied Mathematics - I', subjectCode: 'MAT 101', facultyName: 'Dr. Alok Jain', facultyCode: 'ALK' },
            { id: 'LUNCH', fromTime: '12:15', toTime: '13:10' },
            { id: 'L4', fromTime: '13:15', toTime: '14:10', subjectName: 'LIBRARY/CCA', subjectCode: 'LIBRARY', facultyName: '', facultyCode: '' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'French - I', subjectCode: 'FLU 144', facultyName: 'Dr. Suketu Revar', facultyCode: 'SKR' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'WP LAB (Group 1) / PPS LAB (Group 2)', subjectCode: 'BME 124 / CSE 124', facultyName: 'Dr. Susheel Pandey / Dr. Ganesh Gupta', facultyCode: 'SHP / GGP' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'WP LAB (Group 1) / PPS LAB (Group 2)', subjectCode: 'BME 124 / CSE 124', facultyName: 'Dr. Susheel Pandey / Dr. Ganesh Gupta', facultyCode: 'SHP / GGP' },
        ],
        Thursday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Applied Mathematics - I', subjectCode: 'MAT 101', facultyName: 'Dr. Alok Jain', facultyCode: 'ALK' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'Environmental Studies - I', subjectCode: 'EVS 142', facultyName: 'Dr. Abhishek Kumar', facultyCode: 'ABB' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Basic Mechanical Engineering', subjectCode: 'BME 101', facultyName: 'Dr. Susheel Pandey', facultyCode: 'SHP' },
            { id: 'LUNCH', fromTime: '12:15', toTime: '13:10' },
            { id: 'L4', fromTime: '13:15', toTime: '14:10', subjectName: 'AP LAB - I (Group 2)', subjectCode: 'PHY 121', facultyName: 'Dr. Nirbhay Singh', facultyCode: 'NBS' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'AP LAB - I (Group 2)', subjectCode: 'PHY 121', facultyName: 'Dr. Nirbhay Singh', facultyCode: 'NBS' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'Basic Civil Engineering & Applied Mechanics', subjectCode: 'CIV 101', facultyName: 'Dr. Imran Ahmad', facultyCode: 'IMN' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'Applied Physics - I', subjectCode: 'PHY 101', facultyName: 'Dr. Nirbhay Singh', facultyCode: 'NBS' },
        ],
        Friday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Programming for Problem Solving', subjectCode: 'CSE 104', facultyName: 'Dr. Ganesh Gupta', facultyCode: 'GGP' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'Behavioural Science - I', subjectCode: 'BSU 143', facultyName: 'Dr. Vishakha', facultyCode: 'VSK' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'LIBRARY/CCA', subjectCode: 'LIBRARY', facultyName: '', facultyCode: '' },
            { id: 'LUNCH', fromTime: '12:15', toTime: '13:10' },
            { id: 'L4', fromTime: '13:15', toTime: '14:10', subjectName: 'Applied Mathematics - I', subjectCode: 'MAT 101', facultyName: 'Dr. Alok Jain', facultyCode: 'ALK' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'Basic Mechanical Engineering', subjectCode: 'BME 101', facultyName: 'Dr. Susheel Pandey', facultyCode: 'SHP' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'AP LAB - I (Group 1)', subjectCode: 'PHY 121', facultyName: 'Dr. Nirbhay Singh', facultyCode: 'NBS' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'AP LAB - I (Group 1)', subjectCode: 'PHY 121', facultyName: 'Dr. Nirbhay Singh', facultyCode: 'NBS' },
        ],
        Saturday: [],
        Sunday: [],
    },
};
const btechIt1A_Timetable: TimetableData = {
    course: 'B.Tech',
    program: 'IT',
    semester: '1',
    section: 'A',
    schedule: {
        Monday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Applied Mathematics - I', subjectCode: 'MAT 101', facultyName: 'Dr. Ram Kumar', facultyCode: 'RMK' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'Applied Chemistry', subjectCode: 'CHE-101', facultyName: 'Dr Rachana Kathal', facultyCode: 'RCH' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Programming for Problem Solving', subjectCode: 'CSE 104', facultyName: 'Dr. Ganesh Gupta', facultyCode: 'GGP' },
            { id: 'L4', fromTime: '12:15', toTime: '13:10', subjectName: 'LUNCH', subjectCode: 'LUNCH', facultyName: '', facultyCode: '' },
            { id: 'L5', fromTime: '13:15', toTime: '14:10', subjectName: 'Environmental Studies - I', subjectCode: 'EVS 142', facultyName: 'Dr Rwitabrata M', facultyCode: 'RWM' },
            { id: 'L6', fromTime: '14:15', toTime: '15:10', subjectName: 'Basic Mechanical Engineering', subjectCode: 'BME 101', facultyName: 'Dr. Nasir Khan', facultyCode: 'NSR' },
            { id: 'L7', fromTime: '15:15', toTime: '16:10', subjectName: 'French - I', subjectCode: 'FLU 144', facultyName: 'Mr. Balkishan', facultyCode: 'BLK' },
            { id: 'L8', fromTime: '16:15', toTime: '17:10', subjectName: 'LIBRARY/CCA', subjectCode: 'LIBRARY/CCA', facultyName: '', facultyCode: '' },
        ],
        Tuesday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Applied Chemistry', subjectCode: 'CHE-101', facultyName: 'Dr Rachana Kathal', facultyCode: 'RCH' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'Workshop/Manufacturing Practices Lab / PPS Lab', subjectCode: 'BME 124 / CSE 124', facultyName: '', facultyCode: '' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Workshop/Manufacturing Practices Lab / PPS Lab', subjectCode: 'BME 124 / CSE 124', facultyName: '', facultyCode: '' },
            { id: 'L4', fromTime: '12:15', toTime: '13:10', subjectName: 'LUNCH', subjectCode: 'LUNCH', facultyName: '', facultyCode: '' },
            { id: 'L5', fromTime: '13:15', toTime: '14:10', subjectName: 'Environmental Studies - I', subjectCode: 'EVS 142', facultyName: 'Dr Rwitabrata M', facultyCode: 'RWM' },
            { id: 'L6', fromTime: '14:15', toTime: '15:10', subjectName: 'Applied Mathematics - I', subjectCode: 'MAT 101', facultyName: 'Dr. Ram Kumar', facultyCode: 'RMK' },
            { id: 'L7', fromTime: '15:15', toTime: '16:10', subjectName: 'LIBRARY/CCA', subjectCode: 'LIBRARY/CCA', facultyName: '', facultyCode: '' },
            { id: 'L8', fromTime: '16:15', toTime: '17:10', subjectName: 'Basic Civil Engineering_Applied Mechanics', subjectCode: 'CIV 101', facultyName: 'Mr. Sachin Tiwari', facultyCode: 'SCH' },
        ],
        Wednesday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Applied Chemistry', subjectCode: 'CHE-101', facultyName: 'Dr Rachana Kathal', facultyCode: 'RCH' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'PPS Lab / Applied Chemistry Lab', subjectCode: 'CSE 124 / CHE 121', facultyName: '', facultyCode: '' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'PPS Lab / Applied Chemistry Lab', subjectCode: 'CSE 124 / CHE 121', facultyName: '', facultyCode: '' },
            { id: 'L4', fromTime: '12:15', toTime: '13:10', subjectName: 'LUNCH', subjectCode: 'LUNCH', facultyName: '', facultyCode: '' },
            { id: 'L5', fromTime: '13:15', toTime: '14:10', subjectName: 'Applied Mathematics - I', subjectCode: 'MAT 101', facultyName: 'Dr. Ram Kumar', facultyCode: 'RMK' },
            { id: 'L6', fromTime: '14:15', toTime: '15:10', subjectName: 'Communication Skills - I', subjectCode: 'BCU 141', facultyName: 'Dr. Sonia Srivastav', facultyCode: 'SSV' },
            { id: 'L7', fromTime: '15:15', toTime: '16:10', subjectName: 'LIBRARY/CCA', subjectCode: 'LIBRARY/CCA', facultyName: '', facultyCode: '' },
            { id: 'L8', fromTime: '16:15', toTime: '17:10', subjectName: 'LIBRARY/CCA', subjectCode: 'LIBRARY/CCA', facultyName: '', facultyCode: '' },
        ],
        Thursday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Programming for Problem Solving', subjectCode: 'CSE 104', facultyName: 'Dr. Ganesh Gupta', facultyCode: 'GGP' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'Basic Mechanical Engineering', subjectCode: 'BME 101', facultyName: 'Dr. Nasir Khan', facultyCode: 'NSR' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Behavioural Science - I', subjectCode: 'BSU 143', facultyName: 'Dr. Shubhangi Gup', facultyCode: 'SHG' },
            { id: 'L4', fromTime: '12:15', toTime: '13:10', subjectName: 'LUNCH', subjectCode: 'LUNCH', facultyName: '', facultyCode: '' },
            { id: 'L5', fromTime: '13:15', toTime: '14:10', subjectName: 'Basic Civil Engineering_Applied Mechanics', subjectCode: 'CIV 101', facultyName: 'Mr. Sachin Tiwari', facultyCode: 'SCH' },
            { id: 'L6', fromTime: '14:15', toTime: '15:10', subjectName: 'Communication Skills - I', subjectCode: 'BCU 141', facultyName: 'Dr. Sonia Srivastav', facultyCode: 'SSV' },
            { id: 'L7', fromTime: '15:15', toTime: '16:10', subjectName: 'LIBRARY/CCA', subjectCode: 'LIBRARY/CCA', facultyName: '', facultyCode: '' },
            { id: 'L8', fromTime: '16:15', toTime: '17:10', subjectName: 'LIBRARY/CCA', subjectCode: 'LIBRARY/CCA', facultyName: '', facultyCode: '' },
        ],
        Friday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Basic Mechanical Engineering', subjectCode: 'BME 101', facultyName: 'Dr. Nasir Khan', facultyCode: 'NSR' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'Applied Chemistry Lab / Workshop/Manufacturing Practices Lab', subjectCode: 'CHE 121 / BME 124', facultyName: '', facultyCode: '' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Applied Chemistry Lab / Workshop/Manufacturing Practices Lab', subjectCode: 'CHE 121 / BME 124', facultyName: '', facultyCode: '' },
            { id: 'L4', fromTime: '12:15', toTime: '13:10', subjectName: 'LUNCH', subjectCode: 'LUNCH', facultyName: '', facultyCode: '' },
            { id: 'L5', fromTime: '13:15', toTime: '14:10', subjectName: 'Programming for Problem Solving', subjectCode: 'CSE 104', facultyName: 'Dr. Ganesh Gupta', facultyCode: 'GGP' },
            { id: 'L6', fromTime: '14:15', toTime: '15:10', subjectName: 'Applied Mathematics - I', subjectCode: 'MAT 101', facultyName: 'Dr. Ram Kumar', facultyCode: 'RMK' },
            { id: 'L7', fromTime: '15:15', toTime: '16:10', subjectName: 'Applied Chemistry', subjectCode: 'CHE-101', facultyName: 'Dr Rachana Kathal', facultyCode: 'RCH' },
            { id: 'L8', fromTime: '16:15', toTime: '17:10', subjectName: 'LIBRARY/CCA', subjectCode: 'LIBRARY/CCA', facultyName: '', facultyCode: '' },
        ],
        Saturday: [],
        Sunday: [],
    },
};
const btechIt1B_Timetable: TimetableData = {
    course: 'B.Tech',
    program: 'IT',
    semester: '1',
    section: 'B',
    schedule: {
        Monday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Applied Chemistry', subjectCode: 'CHE-101', facultyName: 'Dr. Rachana Kathal', facultyCode: 'RCH' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'LIBRARY/CCA', subjectCode: 'LIBRARY/CCA', facultyName: '', facultyCode: '' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Basic Mechanical Engineering', subjectCode: 'BME 101', facultyName: 'Mr. Nagendra Kr Sha', facultyCode: 'NGD' },
            { id: 'LUNCH', fromTime: '12:15', toTime: '13:10' },
            { id: 'L4', fromTime: '13:15', toTime: '14:10', subjectName: 'Behavioural Science - I', subjectCode: 'BSU 143', facultyName: 'Dr. Shubhangi Gupta', facultyCode: 'SHG' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'Applied Mathematics - I', subjectCode: 'MAT 101', facultyName: 'Dr. Rajat Vaish', facultyCode: 'RJT' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'LIBRARY/CCA', subjectCode: 'LIBRARY/CCA', facultyName: '', facultyCode: '' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'LIBRARY/CCA', subjectCode: 'LIBRARY/CCA', facultyName: '', facultyCode: '' },
        ],
        Tuesday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Basic Civil Engineering_Applied Mechanics', subjectCode: 'CIV 101', facultyName: 'Dr. Saurabh Dubey', facultyCode: 'SBD' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'PPS LAB / AC LAB', subjectCode: 'CSE 124 / CHE 121', facultyName: 'Padmini Umariya / Dr. Arti Dwivedi', facultyCode: 'PDM / ARD' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'PPS LAB / AC LAB', subjectCode: 'CSE 124 / CHE 121', facultyName: 'Padmini Umariya / Dr. Arti Dwivedi', facultyCode: 'PDM / ARD' },
            { id: 'LUNCH', fromTime: '12:15', toTime: '13:10' },
            { id: 'L4', fromTime: '13:15', toTime: '14:10', subjectName: 'Applied Mathematics - I', subjectCode: 'MAT 101', facultyName: 'Dr. Rajat Vaish', facultyCode: 'RJT' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'Programming for Problem Solving', subjectCode: 'CSE 104', facultyName: 'Padmini Umariya', facultyCode: 'PDM' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'Environmental Studies - I', subjectCode: 'EVS 142', facultyName: 'Dr. Nidhi Shukla', facultyCode: 'NDS' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'Basic Mechanical Engineering', subjectCode: 'BME 101', facultyName: 'Mr. Nagendra Kr Sha', facultyCode: 'NGD' },
        ],
        Wednesday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Basic Mechanical Engineering', subjectCode: 'BME 101', facultyName: 'Mr. Nagendra Kr Sha', facultyCode: 'NGD' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'Applied Mathematics - I', subjectCode: 'MAT 101', facultyName: 'Dr. Rajat Vaish', facultyCode: 'RJT' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Programming for Problem Solving', subjectCode: 'CSE 104', facultyName: 'Padmini Umariya', facultyCode: 'PDM' },
            { id: 'LUNCH', fromTime: '12:15', toTime: '13:10' },
            { id: 'L4', fromTime: '13:15', toTime: '14:10', subjectName: 'LIBRARY/CCA', subjectCode: 'LIBRARY/CCA', facultyName: '', facultyCode: '' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'Communication Skills - I', subjectCode: 'BCU 141', facultyName: 'Dr. Aswathi Menon', facultyCode: 'ASM' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'Applied Chemistry', subjectCode: 'CHE-101', facultyName: 'Dr. Rachana Kathal', facultyCode: 'RCH' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'LIBRARY/CCA', subjectCode: 'LIBRARY/CCA', facultyName: '', facultyCode: '' },
        ],
        Thursday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Applied Chemistry', subjectCode: 'CHE-101', facultyName: 'Dr. Rachana Kathal', facultyCode: 'RCH' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'LIBRARY/CCA', subjectCode: 'LIBRARY/CCA', facultyName: '', facultyCode: '' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Programming for Problem Solving', subjectCode: 'CSE 104', facultyName: 'Padmini Umariya', facultyCode: 'PDM' },
            { id: 'LUNCH', fromTime: '12:15', toTime: '13:10' },
            { id: 'L4', fromTime: '13:15', toTime: '14:10', subjectName: 'French - I', subjectCode: 'FLU 144', facultyName: 'Dr. Suketu Revar', facultyCode: 'SKR' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'Communication Skills - I', subjectCode: 'BCU 141', facultyName: 'Dr. Aswathi Menon', facultyCode: 'ASM' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'WP LAB / PPS LAB', subjectCode: 'BME 124 / CSE 124', facultyName: '', facultyCode: '' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'WP LAB / PPS LAB', subjectCode: 'BME 124 / CSE 124', facultyName: '', facultyCode: '' },
        ],
        Friday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Applied Chemistry', subjectCode: 'CHE-101', facultyName: 'Dr. Rachana Kathal', facultyCode: 'RCH' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'Applied Mathematics - I', subjectCode: 'MAT 101', facultyName: 'Dr. Rajat Vaish', facultyCode: 'RJT' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Basic Civil Engineering_Applied Mechanics', subjectCode: 'CIV 101', facultyName: 'Dr. Saurabh Dubey', facultyCode: 'SBD' },
            { id: 'LUNCH', fromTime: '12:15', toTime: '13:10' },
            { id: 'L4', fromTime: '13:15', toTime: '14:10', subjectName: 'AC LAB / WP LAB', subjectCode: 'CHE 121 / BME 124', facultyName: '', facultyCode: '' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'AC LAB / WP LAB', subjectCode: 'CHE 121 / BME 124', facultyName: '', facultyCode: '' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'Environmental Studies - I', subjectCode: 'EVS 142', facultyName: 'Dr. Nidhi Shukla', facultyCode: 'NDS' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'LIBRARY/CCA', subjectCode: 'LIBRARY/CCA', facultyName: '', facultyCode: '' },
        ],
        Saturday: [],
        Sunday: [],
    },
};

    
const btechCse3A_Timetable: TimetableData = {
    course: 'B.Tech',
    program: 'CSE',
    semester: '3',
    section: 'A',
    schedule: {
        Monday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Python Programming', subjectCode: 'CSE302', facultyName: 'Dr. Ghanshyam P', facultyCode: '' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'Applied Mathematics - III', subjectCode: 'MAT 301', facultyName: 'Dr. Giriraj Kumar', facultyCode: '' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Digital Electronics and Logic Design', subjectCode: 'ECE 306', facultyName: 'Ms. Rashmi Tikar', facultyCode: '' },
            { id: 'L4', fromTime: '12:15', toTime: '13:10', subjectName: 'Data Structures Through C++', subjectCode: 'CSE 202', facultyName: 'Mr. Gaurav Kumar', facultyCode: '' },
            { id: 'LUNCH', fromTime: '13:10', toTime: '14:10' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'Behavioural Science - III', subjectCode: 'BSU 343', facultyName: 'Dr. Jangjeet', facultyCode: '' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'CSE Specialization', subjectCode: 'CSE Spec.', facultyName: '', facultyCode: '' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'Database Management Systems', subjectCode: 'CSE 304', facultyName: 'Ms. Nishtha Paras', facultyCode: '' },
        ],
        Tuesday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'CSE Specialization', subjectCode: 'CSE Spec.', facultyName: '', facultyCode: '' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'Python Programming Lab', subjectCode: 'CSE 322', facultyName: 'Arunima Shivhare', facultyCode: '' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'DBMS Lab', subjectCode: 'CSE 324', facultyName: 'Jeetendra Singh Bh', facultyCode: '' },
            { id: 'L4', fromTime: '12:15', toTime: '13:10', subjectName: 'French - III', subjectCode: 'FLU 344', facultyName: 'Dr. Suketu Revar', facultyCode: '' },
            { id: 'LUNCH', fromTime: '13:10', toTime: '14:10' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'DBMS Lab', subjectCode: 'CSE 324', facultyName: 'Jeetendra Singh Bh', facultyCode: '' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'Data Structures through C++ Lab', subjectCode: 'CSE 222', facultyName: 'Dr. Giriraj Kumar', facultyCode: '' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'LIBRARY/CCA', subjectCode: 'LIBRARY', facultyName: '', facultyCode: '' },
        ],
        Wednesday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Digital Electronics and Logic Design Lab', subjectCode: 'ECE 326', facultyName: 'Ms. Rashmi Tikar', facultyCode: '' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'Python Programming Lab', subjectCode: 'CSE 322', facultyName: 'Arunima Shivhare', facultyCode: '' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Database Management Systems', subjectCode: 'CSE 304', facultyName: 'Ms. Nishtha Paras', facultyCode: '' },
            { id: 'L4', fromTime: '12:15', toTime: '13:10', subjectName: 'Python Programming', subjectCode: 'CSE302', facultyName: 'Dr. Ghanshyam P', facultyCode: '' },
            { id: 'LUNCH', fromTime: '13:10', toTime: '14:10' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'Communication Skills - III', subjectCode: 'BSU 341', facultyName: 'Dr. Archana Sharn', facultyCode: '' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'CSE Specialization', subjectCode: 'CSE Spec.', facultyName: '', facultyCode: '' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'LIBRARY/CCA', subjectCode: 'LIBRARY', facultyName: '', facultyCode: '' },
        ],
        Thursday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'CSE Specialization', subjectCode: 'CSE Spec.', facultyName: '', facultyCode: '' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'CSE Specialization', subjectCode: 'CSE Spec.', facultyName: '', facultyCode: '' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Data Structures Through C++', subjectCode: 'CSE 202', facultyName: 'Mr. Gaurav Kumar', facultyCode: '' },
            { id: 'L4', fromTime: '12:15', toTime: '13:10', subjectName: 'Digital Electronics and Logic Design', subjectCode: 'ECE 306', facultyName: 'Ms. Rashmi Tikar', facultyCode: '' },
            { id: 'LUNCH', fromTime: '13:10', toTime: '14:10' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'Communication Skills - III', subjectCode: 'BSU 341', facultyName: 'Dr. Archana Sharn', facultyCode: '' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'Python Programming', subjectCode: 'CSE302', facultyName: 'Dr. Ghanshyam P', facultyCode: '' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'Applied Mathematics - III', subjectCode: 'MAT 301', facultyName: 'Dr. Giriraj Kumar', facultyCode: '' },
        ],
        Friday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Applied Mathematics - III', subjectCode: 'MAT 301', facultyName: 'Dr. Giriraj Kumar', facultyCode: '' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'Database Management Systems', subjectCode: 'CSE 304', facultyName: 'Ms. Nishtha Paras', facultyCode: '' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Data Structures Through C++', subjectCode: 'CSE 202', facultyName: 'Mr. Gaurav Kumar', facultyCode: '' },
            { id: 'L4', fromTime: '12:15', toTime: '13:10', subjectName: 'Digital Electronics and Logic Design', subjectCode: 'ECE 306', facultyName: 'Ms. Rashmi Tikar', facultyCode: '' },
            { id: 'LUNCH', fromTime: '13:10', toTime: '14:10' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'Data Structures through C++ Lab', subjectCode: 'CSE 222', facultyName: 'Mr. Gaurav Kumar', facultyCode: '' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'Digital Electronics and Logic Design Lab', subjectCode: 'ECE 326', facultyName: 'Ms. Rashmi Tikar', facultyCode: '' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'LIBRARY/CCA', subjectCode: 'LIBRARY', facultyName: '', facultyCode: '' },
        ],
        Saturday: [],
        Sunday: [],
    },
};

const btechCse3B_Timetable: TimetableData = {
    course: 'B.Tech',
    program: 'CSE',
    semester: '3',
    section: 'B',
    schedule: {
        Monday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Database Management Systems Lab', subjectCode: 'CSE 324', facultyName: 'Ms. Nishtha Paras', facultyCode: '' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'Python Programming Lab', subjectCode: 'CSE 322', facultyName: 'Dr. Ashok Kr Shrivastava', facultyCode: '' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Python Programming', subjectCode: 'CSE302', facultyName: 'Dr. Ashok Kr Shrivastava', facultyCode: '' },
            { id: 'L4', fromTime: '12:15', toTime: '13:10', subjectName: 'Digital Electronics and Logic Design', subjectCode: 'ECE 306', facultyName: 'Ms. Rashmi Tikar', facultyCode: '' },
            { id: 'LUNCH', fromTime: '13:10', toTime: '14:10' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'Database Management Systems', subjectCode: 'CSE 304', facultyName: 'Ms. Nishtha Paras', facultyCode: '' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'CSE Specialization', subjectCode: 'CSE SPEC.', facultyName: '', facultyCode: '' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'LIBRARY/CCA', subjectCode: 'LIBRARY/CCA', facultyName: '', facultyCode: '' },
        ],
        Tuesday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'CSE Specialization', subjectCode: 'CSE SPEC.', facultyName: '', facultyCode: '' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'Data Structures Through C++', subjectCode: 'CSE 202', facultyName: 'Mr. Gaurav Kumar', facultyCode: '' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Python Programming Lab', subjectCode: 'CSE 322', facultyName: 'Dr. Ashok Kr Shrivastava', facultyCode: '' },
            { id: 'L4', fromTime: '12:15', toTime: '13:10', subjectName: 'Data Structures through C++ Lab', subjectCode: 'CSE 222', facultyName: 'Mr. Gaurav Kumar', facultyCode: '' },
            { id: 'LUNCH', fromTime: '13:10', toTime: '14:10' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'Applied Mathematics - III', subjectCode: 'MAT 301', facultyName: 'Dr. Rajat Vaish', facultyCode: '' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'Digital Electronics and Logic Design Lab', subjectCode: 'ECE 326', facultyName: 'Ms. Rashmi Tikar', facultyCode: '' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'Database Management Systems Lab', subjectCode: 'CSE 324', facultyName: 'Ms. Nishtha Paras', facultyCode: '' },
        ],
        Wednesday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Python Programming', subjectCode: 'CSE302', facultyName: 'Dr. Ashok Kr Shrivastava', facultyCode: '' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'Behavioural Science - III', subjectCode: 'BSU 343', facultyName: 'Ms. Rashmi Tikar', facultyCode: '' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Digital Electronics and Logic Design', subjectCode: 'ECE 306', facultyName: 'Ms. Rashmi Tikar', facultyCode: '' },
            { id: 'L4', fromTime: '12:15', toTime: '13:10', subjectName: 'French - III', subjectCode: 'FLU 344', facultyName: 'Dr. Suketu Revar', facultyCode: '' },
            { id: 'LUNCH', fromTime: '13:10', toTime: '14:10' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'Data Structures Through C++', subjectCode: 'CSE 202', facultyName: 'Mr. Gaurav Kumar', facultyCode: '' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'CSE Specialization', subjectCode: 'CSE SPEC.', facultyName: '', facultyCode: '' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'Database Management Systems', subjectCode: 'CSE 304', facultyName: 'Ms. Nishtha Paras', facultyCode: '' },
        ],
        Thursday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'CSE Specialization', subjectCode: 'CSE SPEC.', facultyName: '', facultyCode: '' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'CSE Specialization', subjectCode: 'CSE SPEC.', facultyName: '', facultyCode: '' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Digital Electronics and Logic Design', subjectCode: 'ECE 306', facultyName: 'Ms. Rashmi Tikar', facultyCode: '' },
            { id: 'L4', fromTime: '12:15', toTime: '13:10', subjectName: 'Data Structures Through C++', subjectCode: 'CSE 202', facultyName: 'Mr. Gaurav Kumar', facultyCode: '' },
            { id: 'LUNCH', fromTime: '13:10', toTime: '14:10' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'Communication Skills - III', subjectCode: 'BSU 341', facultyName: 'Dr. Monika Saxena', facultyCode: '' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'Applied Mathematics - III', subjectCode: 'MAT 301', facultyName: 'Dr. Rajat Vaish', facultyCode: '' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'LIBRARY/CCA', subjectCode: 'LIBRARY/CCA', facultyName: '', facultyCode: '' },
        ],
        Friday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Data Structures through C++ Lab', subjectCode: 'CSE 222', facultyName: 'Mr. Gaurav Kumar', facultyCode: '' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'Digital Electronics and Logic Design Lab', subjectCode: 'ECE 326', facultyName: 'Ms. Rashmi Tikar', facultyCode: '' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Database Management Systems', subjectCode: 'CSE 304', facultyName: 'Ms. Nishtha Paras', facultyCode: '' },
            { id: 'L4', fromTime: '12:15', toTime: '13:10', subjectName: 'Python Programming', subjectCode: 'CSE302', facultyName: 'Dr. Ashok Kr Shrivastava', facultyCode: '' },
            { id: 'LUNCH', fromTime: '13:10', toTime: '14:10' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'Communication Skills - III', subjectCode: 'BSU 341', facultyName: 'Dr. Monika Saxena', facultyCode: '' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'Applied Mathematics - III', subjectCode: 'MAT 301', facultyName: 'Dr. Rajat Vaish', facultyCode: '' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'LIBRARY/CCA', subjectCode: 'LIBRARY/CCA', facultyName: '', facultyCode: '' },
        ],
        Saturday: [],
        Sunday: [],
    },
};

const btechCse3C_Timetable: TimetableData = {
    course: 'B.Tech',
    program: 'CSE',
    semester: '3',
    section: 'C',
    schedule: {
        Monday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Digital Electronics and Logic Design', subjectCode: 'ECE 306', facultyName: 'Ms. Rashmi Tikar', facultyCode: 'RSH' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'Applied Mathematics - III', subjectCode: 'MAT 301', facultyName: 'Dr. Rajat Vaish', facultyCode: 'RJT' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'LIBRARY/CCA', subjectCode: 'LIBRARY/CCA', facultyName: '', facultyCode: '' },
            { id: 'L4', fromTime: '12:15', toTime: '13:10', subjectName: 'Behavioural Science - III', subjectCode: 'BSU 341', facultyName: 'A.Daniel', facultyCode: 'CS_VF' },
            { id: 'LUNCH', fromTime: '13:10', toTime: '14:10' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'French - III', subjectCode: 'FLU 344', facultyName: 'Mr. Balkishan', facultyCode: 'BLK' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'CSE Specialization', subjectCode: 'CSE Spec.', facultyName: '', facultyCode: '' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'Python Programming', subjectCode: 'CSE 302/CSE510', facultyName: 'Dr. Ashok Kr Shrivast', facultyCode: 'ASK' },
        ],
        Tuesday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'CSE Specialization', subjectCode: 'CSE Spec.', facultyName: '', facultyCode: '' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'Python Programming', subjectCode: 'CSE 302/CSE510', facultyName: 'Dr. Ashok Kr Shrivast', facultyCode: 'ASK' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Digital Electronics and Logic Design', subjectCode: 'ECE 306', facultyName: 'Ms. Rashmi Tikar', facultyCode: 'RSH' },
            { id: 'L4', fromTime: '12:15', toTime: '13:10', subjectName: 'Behavioural Science - III', subjectCode: 'BSU 341', facultyName: 'A.Daniel', facultyCode: 'CS_VF' },
            { id: 'LUNCH', fromTime: '13:10', toTime: '14:10' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'Data Structures Through C++', subjectCode: 'CSE 202', facultyName: 'A.Daniel', facultyCode: 'DAN' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'LIBRARY/CCA', subjectCode: 'LIBRARY/CCA', facultyName: '', facultyCode: '' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'Python Programming Lab', subjectCode: 'CSE 322/ CSE 530', facultyName: 'Arunima Shivhare', facultyCode: 'ARM' },
        ],
        Wednesday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Database Management Systems', subjectCode: 'CSE 304', facultyName: 'Ms. Nishtha Parashar', facultyCode: 'NST' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'Python Programming', subjectCode: 'CSE 302/CSE510', facultyName: 'Dr. Ashok Kr Shrivast', facultyCode: 'ASK' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Applied Mathematics - III', subjectCode: 'MAT 301', facultyName: 'Dr. Rajat Vaish', facultyCode: 'RJT' },
            { id: 'L4', fromTime: '12:15', toTime: '13:10', subjectName: 'Database Management Systems', subjectCode: 'CSE 304', facultyName: 'Ms. Nishtha Parashar', facultyCode: 'NST' },
            { id: 'LUNCH', fromTime: '13:10', toTime: '14:10' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'Digital Electronics and Logic Design', subjectCode: 'ECE 306', facultyName: 'Ms. Rashmi Tikar', facultyCode: 'RSH' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'CSE Specialization', subjectCode: 'CSE Spec.', facultyName: '', facultyCode: '' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'Data Structures Through C++', subjectCode: 'CSE 202', facultyName: 'A.Daniel', facultyCode: 'DAN' },
        ],
        Thursday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'CSE Specialization', subjectCode: 'CSE Spec.', facultyName: '', facultyCode: '' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'CSE Specialization', subjectCode: 'CSE Spec.', facultyName: '', facultyCode: '' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Digital Electronics and Logic Design Lab', subjectCode: 'ECE 326', facultyName: 'Dr. Rinkoo Bhatia', facultyCode: 'RNK' },
            { id: 'L4', fromTime: '12:15', toTime: '13:10', subjectName: 'Database Management Systems Lab', subjectCode: 'CSE 324', facultyName: 'Jeetendra Singh Bhad', facultyCode: 'JTS' },
            { id: 'LUNCH', fromTime: '13:10', toTime: '14:10' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'Database Management Systems Lab', subjectCode: 'CSE 324', facultyName: 'Jeetendra Singh Bhad', facultyCode: 'JTS' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'LIBRARY/CCA', subjectCode: 'LIBRARY/CCA', facultyName: '', facultyCode: '' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'Database Management Systems', subjectCode: 'CSE 304', facultyName: 'Ms. Nishtha Parashar', facultyCode: 'NST' },
        ],
        Friday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Applied Mathematics - III', subjectCode: 'MAT 301', facultyName: 'Dr. Rajat Vaish', facultyCode: 'RJT' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'Behavioural Science - III', subjectCode: 'BSU 343', facultyName: 'Dr. Vikas Sharma', facultyCode: 'VSH' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Python Programming Lab', subjectCode: 'CSE 322/ CSE 530', facultyName: 'Arunima Shivhare', facultyCode: 'ARM' },
            { id: 'L4', fromTime: '12:15', toTime: '13:10', subjectName: 'Digital Electronics and Logic Design Lab', subjectCode: 'ECE 326', facultyName: 'Dr. Rinkoo Bhatia', facultyCode: 'RNK' },
            { id: 'LUNCH', fromTime: '13:10', toTime: '14:10' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'Data Structures Through C++', subjectCode: 'CSE 202', facultyName: 'A.Daniel', facultyCode: 'DAN' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'LIBRARY/CCA', subjectCode: 'LIBRARY/CCA', facultyName: '', facultyCode: '' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'LIBRARY/CCA', subjectCode: 'LIBRARY/CCA', facultyName: '', facultyCode: '' },
        ],
        Saturday: [],
        Sunday: [],
    },
};

export const defaultTimetables: Record<string, TimetableData> = {
   'B.Tech-CSE-1-A': btechCse1A_Timetable,
   'B.Tech-CSE-1-B': btechCse1B_Timetable,
    'B.Tech-CSE-1-C': btechCse1C_Timetable,
    'B.Tech-IT-1-A': btechIt1A_Timetable,
    'B.Tech-IT-1-B': btechIt1B_Timetable,


    'B.Tech-CSE-3-A': btechCse3A_Timetable,
    'B.Tech-CSE-3-B': btechCse3B_Timetable,
    'B.Tech-CSE-3-C': btechCse3C_Timetable,
};




