
import type { TimetableData } from "@/app/timetable/page";

const btechCse1A_Timetable: TimetableData = {
    course: 'B.Tech',
    program: 'CSE',
    semester: '1',
    section: 'A',
    schedule: {
        Monday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Applied Mathematics - I', subjectCode: 'MAT 101', facultyName: 'Dr. Santosh Kr Sharm', facultyCode: 'SNT' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'Basic Civil Eng. & Applied Mechanics', subjectCode: 'CIV 101', facultyName: 'Mr. Sachin Tiwari', facultyCode: 'SCH' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Applied Physics - I', subjectCode: 'PHY 101', facultyName: 'Dr. Pankaj Mishra', facultyCode: 'PKM' },
            { id: 'LUNCH', fromTime: '12:15', toTime: '13:10' },
            { id: 'L4', fromTime: '13:15', toTime: '14:10', subjectName: 'PPS Lab', subjectCode: 'CSE 124', facultyName: 'Dr. C.S. Raghuvanshi', facultyCode: 'CSR' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'Workshop/Manufacturing Practices Lab', subjectCode: 'BME 124', facultyName: 'Ms. Apoorva Sharma', facultyCode: 'ASP' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'LIBRARY/CCA', subjectCode: '', facultyName: '', facultyCode: '' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'LIBRARY/CCA', subjectCode: '', facultyName: '', facultyCode: '' },
        ],
        Tuesday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Communication Skills - I', subjectCode: 'BCU 141', facultyName: 'Dr. Monika Saxena', facultyCode: 'MKS' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'Programming for Problem Solving', subjectCode: 'CSE 104', facultyName: 'Dr. C.S. Raghuvanshi', facultyCode: 'CSR' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Applied Mathematics - I', subjectCode: 'MAT 101', facultyName: 'Dr. Santosh Kr Sharm', facultyCode: 'SNT' },
            { id: 'LUNCH', fromTime: '12:15', toTime: '13:10' },
            { id: 'L4', fromTime: '13:15', toTime: '14:10', subjectName: 'Basic Mechanical Engineering', subjectCode: 'BME 101', facultyName: 'Dr. Ashish Singh Pare', facultyCode: 'ASP' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'Environmental Studies - I', subjectCode: 'EVS 142', facultyName: 'Dr. Nidhi Shukla', facultyCode: 'NDS' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'French - I', subjectCode: 'FLU 144', facultyName: 'Dr. Neelam Singh Ton', facultyCode: 'NLT' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'Applied Physics Lab - I', subjectCode: 'PHY 121', facultyName: 'Dr. Manisha Singh', facultyCode: 'MNS' },
        ],
        Wednesday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Behavioural Science - I', subjectCode: 'BSU 143', facultyName: 'Dr Shubhagata Awasti', facultyCode: 'SBA' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'Applied Physics - I', subjectCode: 'PHY 101', facultyName: 'Dr. Pankaj Mishra', facultyCode: 'PKM' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Applied Physics Lab - I', subjectCode: 'PHY 121', facultyName: 'Dr. Manisha Singh', facultyCode: 'MNS' },
            { id: 'LUNCH', fromTime: '12:15', toTime: '13:10' },
            { id: 'L4', fromTime: '13:15', toTime: '14:10', subjectName: 'Programming for Problem Solving', subjectCode: 'CSE 104', facultyName: 'Dr. C.S. Raghuvanshi', facultyCode: 'CSR' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'LIBRARY/CCA', subjectCode: '', facultyName: '', facultyCode: '' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'Basic Civil Eng. & Applied Mechanics', subjectCode: 'CIV 101', facultyName: 'Mr. Sachin Tiwari', facultyCode: 'SCH' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'Basic Mechanical Engineering', subjectCode: 'BME 101', facultyName: 'Dr. Ashish Singh Pare', facultyCode: 'ASP' },
        ],
        Thursday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Environmental Studies - I', subjectCode: 'EVS 142', facultyName: 'Dr. Nidhi Shukla', facultyCode: 'NDS' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'Applied Physics - I', subjectCode: 'PHY 101', facultyName: 'Dr. Pankaj Mishra', facultyCode: 'PKM' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Applied Mathematics - I', subjectCode: 'MAT 101', facultyName: 'Dr. Santosh Kr Sharm', facultyCode: 'SNT' },
            { id: 'LUNCH', fromTime: '12:15', toTime: '13:10' },
            { id: 'L4', fromTime: '13:15', toTime: '14:10', subjectName: 'Basic Civil Eng. & Applied Mechanics', subjectCode: 'CIV 101', facultyName: 'Mr. Sachin Tiwari', facultyCode: 'SCH' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'Basic Mechanical Engineering', subjectCode: 'BME 101', facultyName: 'Dr. Ashish Singh Pare', facultyCode: 'ASP' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'Workshop/Manufacturing Practices Lab', subjectCode: 'BME 124', facultyName: 'Ms. Apoorva Sharma', facultyCode: 'ASP' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'PPS Lab', subjectCode: 'CSE 124', facultyName: 'Dr. C.S. Raghuvanshi', facultyCode: 'CSR' },
        ],
        Friday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Programming for Problem Solving', subjectCode: 'CSE 104', facultyName: 'Dr. C.S. Raghuvanshi', facultyCode: 'CSR' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'Behavioural Science - I', subjectCode: 'BSU 143', facultyName: 'Dr Shubhagata Awasti', facultyCode: 'SBA' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Communication Skills - I', subjectCode: 'BCU 141', facultyName: 'Dr. Monika Saxena', facultyCode: 'MKS' },
            { id: 'LUNCH', fromTime: '12:15', toTime: '13:10' },
            { id: 'L4', fromTime: '13:15', toTime: '14:10', subjectName: 'French - I', subjectCode: 'FLU 144', facultyName: 'Dr. Neelam Singh Ton', facultyCode: 'NLT' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'LIBRARY/CCA', subjectCode: '', facultyName: '', facultyCode: '' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'LIBRARY/CCA', subjectCode: '', facultyName: '', facultyCode: '' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'LIBRARY/CCA', subjectCode: '', facultyName: '', facultyCode: '' },
        ],
        Saturday: [],
        Sunday: [],
    }
};

const btechCse1B_Timetable: TimetableData = {
    course: 'B.Tech',
    program: 'CSE',
    semester: '1',
    section: 'B',
    schedule: {
        Monday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Applied Physics - I', subjectCode: 'PHY 101', facultyName: 'Ms. Apoorva Sharma', facultyCode: 'APS' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'PPS LAB (Group 1) / AP LAB - I (Group 2)', subjectCode: 'CSE 124 / PHY 121', facultyName: 'Dr. C.S. Raghuvanshi / Dr. Manisha Singh', facultyCode: 'CSR / MNS' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Basic Mechanical Engineering', subjectCode: 'BME 101', facultyName: 'Ms. Apoorva Sharma', facultyCode: 'ASP' },
            { id: 'LUNCH', fromTime: '12:15', toTime: '13:10' },
            { id: 'L4', fromTime: '13:15', toTime: '14:10', subjectName: 'Environmental Studies - I', subjectCode: 'EVS 142', facultyName: 'Dr. Nidhi Shukla', facultyCode: 'NDS' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'Applied Mathematics - I', subjectCode: 'MAT 101', facultyName: 'Dr. Santosh Kr Sharm', facultyCode: 'SNT' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'Communication Skills - I', subjectCode: 'BCU 141', facultyName: 'Dr. Monika Saxena', facultyCode: 'MKS' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'Programming for Problem Solving', subjectCode: 'CSE 104', facultyName: 'Dr. C.S. Raghuvanshi', facultyCode: 'CSR' },
        ],
        Tuesday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Basic Civil Eng. & Applied Mechanics', subjectCode: 'CIV 101', facultyName: 'Mr. Sachin Tiwari', facultyCode: 'SCH' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'AP LAB - I (Group 1) / LIBRARY/CCA (Group 2)', subjectCode: 'PHY 121', facultyName: 'Dr. Manisha Singh', facultyCode: 'MNS' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Applied Physics - I', subjectCode: 'PHY 101', facultyName: 'Dr. Pankaj Mishra', facultyCode: 'PKM' },
            { id: 'LUNCH', fromTime: '12:15', toTime: '13:10' },
            { id: 'L4', fromTime: '13:15', toTime: '14:10', subjectName: 'Basic Mechanical Engineering', subjectCode: 'BME 101', facultyName: 'Ms. Apoorva Sharma', facultyCode: 'ASP' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'French - I', subjectCode: 'FLU 144', facultyName: 'Dr. Neelam Singh Ton', facultyCode: 'NLT' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'Communication Skills - I', subjectCode: 'BCU 141', facultyName: 'Dr. Monika Saxena', facultyCode: 'MKS' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'Applied Physics - I', subjectCode: 'PHY 101', facultyName: 'Dr. Pankaj Mishra', facultyCode: 'PKM' },
        ],
        Wednesday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Applied Mathematics - I', subjectCode: 'MAT 101', facultyName: 'Dr. Santosh Kr Sharm', facultyCode: 'SNT' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'LIBRARY/CCA', subjectCode: '', facultyName: '', facultyCode: '' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Applied Physics - I', subjectCode: 'PHY 101', facultyName: 'Dr. Pankaj Mishra', facultyCode: 'PKM' },
            { id: 'LUNCH', fromTime: '12:15', toTime: '13:10' },
            { id: 'L4', fromTime: '13:15', toTime: '14:10', subjectName: 'WP LAB (Group 1) / PPS LAB (Group 2)', subjectCode: 'BME 124 / CSE 124', facultyName: 'Ms. Apoorva Sharma / Dr. C.S. Raghuvanshi', facultyCode: 'ASP / CSR' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'LIBRARY/CCA', subjectCode: '', facultyName: '', facultyCode: '' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'LIBRARY/CCA', subjectCode: '', facultyName: '', facultyCode: '' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'LIBRARY/CCA', subjectCode: '', facultyName: '', facultyCode: '' },
        ],
        Thursday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Programming for Problem Solving', subjectCode: 'CSE 104', facultyName: 'Dr. C.S. Raghuvanshi', facultyCode: 'CSR' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'Applied Mathematics - I', subjectCode: 'MAT 101', facultyName: 'Dr. Santosh Kr Sharm', facultyCode: 'SNT' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Behavioural Science - I', subjectCode: 'BSU 143', facultyName: 'Dr Shubhagata Awasti', facultyCode: 'SBA' },
            { id: 'LUNCH', fromTime: '12:15', toTime: '13:10' },
            { id: 'L4', fromTime: '13:15', toTime: '14:10', subjectName: 'LIBRARY/CCA', subjectCode: '', facultyName: '', facultyCode: '' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'Applied Physics - I', subjectCode: 'PHY 101', facultyName: 'Dr. Pankaj Mishra', facultyCode: 'PKM' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'Environmental Studies - I', subjectCode: 'EVS 142', facultyName: 'Dr. Nidhi Shukla', facultyCode: 'NDS' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'LIBRARY/CCA', subjectCode: '', facultyName: '', facultyCode: '' },
        ],
        Friday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Programming for Problem Solving', subjectCode: 'CSE 104', facultyName: 'Dr. C.S. Raghuvanshi', facultyCode: 'CSR' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'Applied Mathematics - I', subjectCode: 'MAT 101', facultyName: 'Dr. Santosh Kr Sharm', facultyCode: 'SNT' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Basic Civil Eng. & Applied Mechanics', subjectCode: 'CIV 101', facultyName: 'Mr. Sachin Tiwari', facultyCode: 'SCH' },
            { id: 'LUNCH', fromTime: '12:15', toTime: '13:10' },
            { id: 'L4', fromTime: '13:15', toTime: '14:10', subjectName: 'Basic Mechanical Engineering', subjectCode: 'BME 101', facultyName: 'Ms. Apoorva Sharma', facultyCode: 'ASP' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'LIBRARY/CCA (Group 1) / WP LAB (Group 2)', subjectCode: 'BME 124', facultyName: 'Ms. Apoorva Sharma', facultyCode: 'ASP' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'LIBRARY/CCA', subjectCode: '', facultyName: '', facultyCode: '' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'LIBRARY/CCA', subjectCode: '', facultyName: '', facultyCode: '' },
        ],
        Saturday: [],
        Sunday: [],
    }
};


const btechCse3A_Timetable: TimetableData = {
    course: 'B.Tech',
    program: 'CSE',
    semester: '3',
    section: 'A',
    schedule: {
        Monday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Python Programming', subjectCode: 'CSE302', facultyName: 'Dr. Ghanshyam P', facultyCode: '' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'Applied Mathematics - III', subjectCode: 'MAT 301', facultyName: 'Dr. Giriraj Kumar', facultyCode: '' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Digital Electronics and Logic Design', subjectCode: 'ECE 306', facultyName: 'Ms. Rashmi Tikar', facultyCode: '' },
            { id: 'L4', fromTime: '12:15', toTime: '13:10', subjectName: 'Data Structures Through C++', subjectCode: 'CSE 202', facultyName: 'Mr. Gaurav Kumar', facultyCode: '' },
            { id: 'LUNCH', fromTime: '13:10', toTime: '14:10' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'Behavioural Science - III', subjectCode: 'BSU 343', facultyName: 'Dr. Jangjeet', facultyCode: '' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'CSE Specialization', subjectCode: 'CSE Spec.', facultyName: '', facultyCode: '' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'Database Management Systems', subjectCode: 'CSE 304', facultyName: 'Ms. Nishtha Paras', facultyCode: '' },
        ],
        Tuesday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'CSE Specialization', subjectCode: 'CSE Spec.', facultyName: '', facultyCode: '' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'Python Programming Lab', subjectCode: 'CSE 322', facultyName: 'Arunima Shivhare', facultyCode: '' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'DBMS Lab', subjectCode: 'CSE 324', facultyName: 'Jeetendra Singh Bh', facultyCode: '' },
            { id: 'L4', fromTime: '12:15', toTime: '13:10', subjectName: 'French - III', subjectCode: 'FLU 344', facultyName: 'Dr. Suketu Revar', facultyCode: '' },
            { id: 'LUNCH', fromTime: '13:10', toTime: '14:10' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'DBMS Lab', subjectCode: 'CSE 324', facultyName: 'Jeetendra Singh Bh', facultyCode: '' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'Data Structures through C++ Lab', subjectCode: 'CSE 222', facultyName: 'Dr. Giriraj Kumar', facultyCode: '' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'LIBRARY/CCA', subjectCode: 'LIBRARY', facultyName: '', facultyCode: '' },
        ],
        Wednesday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Digital Electronics and Logic Design Lab', subjectCode: 'ECE 326', facultyName: 'Ms. Rashmi Tikar', facultyCode: '' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'Python Programming Lab', subjectCode: 'CSE 322', facultyName: 'Arunima Shivhare', facultyCode: '' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Database Management Systems', subjectCode: 'CSE 304', facultyName: 'Ms. Nishtha Paras', facultyCode: '' },
            { id: 'L4', fromTime: '12:15', toTime: '13:10', subjectName: 'Python Programming', subjectCode: 'CSE302', facultyName: 'Dr. Ghanshyam P', facultyCode: '' },
            { id: 'LUNCH', fromTime: '13:10', toTime: '14:10' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'Communication Skills - III', subjectCode: 'BSU 341', facultyName: 'Dr. Archana Sharn', facultyCode: '' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'CSE Specialization', subjectCode: 'CSE Spec.', facultyName: '', facultyCode: '' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'LIBRARY/CCA', subjectCode: 'LIBRARY', facultyName: '', facultyCode: '' },
        ],
        Thursday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'CSE Specialization', subjectCode: 'CSE Spec.', facultyName: '', facultyCode: '' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'CSE Specialization', subjectCode: 'CSE Spec.', facultyName: '', facultyCode: '' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Data Structures Through C++', subjectCode: 'CSE 202', facultyName: 'Mr. Gaurav Kumar', facultyCode: '' },
            { id: 'L4', fromTime: '12:15', toTime: '13:10', subjectName: 'Digital Electronics and Logic Design', subjectCode: 'ECE 306', facultyName: 'Ms. Rashmi Tikar', facultyCode: '' },
            { id: 'LUNCH', fromTime: '13:10', toTime: '14:10' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'Communication Skills - III', subjectCode: 'BSU 341', facultyName: 'Dr. Archana Sharn', facultyCode: '' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'Python Programming', subjectCode: 'CSE302', facultyName: 'Dr. Ghanshyam P', facultyCode: '' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'Applied Mathematics - III', subjectCode: 'MAT 301', facultyName: 'Dr. Giriraj Kumar', facultyCode: '' },
        ],
        Friday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Applied Mathematics - III', subjectCode: 'MAT 301', facultyName: 'Dr. Giriraj Kumar', facultyCode: '' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'Database Management Systems', subjectCode: 'CSE 304', facultyName: 'Ms. Nishtha Paras', facultyCode: '' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Data Structures Through C++', subjectCode: 'CSE 202', facultyName: 'Mr. Gaurav Kumar', facultyCode: '' },
            { id: 'L4', fromTime: '12:15', toTime: '13:10', subjectName: 'Digital Electronics and Logic Design', subjectCode: 'ECE 306', facultyName: 'Ms. Rashmi Tikar', facultyCode: '' },
            { id: 'LUNCH', fromTime: '13:10', toTime: '14:10' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'Data Structures through C++ Lab', subjectCode: 'CSE 222', facultyName: 'Mr. Gaurav Kumar', facultyCode: '' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'Digital Electronics and Logic Design Lab', subjectCode: 'ECE 326', facultyName: 'Ms. Rashmi Tikar', facultyCode: '' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'LIBRARY/CCA', subjectCode: 'LIBRARY', facultyName: '', facultyCode: '' },
        ],
        Saturday: [],
        Sunday: [],
    },
};

export const defaultTimetables: Record<string, TimetableData> = {
    'B.Tech-CSE-1-A': btechCse1A_Timetable,
    'B.Tech-CSE-1-B': btechCse1B_Timetable,
    'B.Tech-CSE-3-A': btechCse3A_Timetable,
};
