
import type { TimetableData } from "@/app/timetable/page";

const btechCse1A_Timetable: TimetableData = {
    course: 'B.Tech',
    program: 'CSE',
    semester: '1',
    section: 'A',
    schedule: {
        Monday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Programming for Problem Solving', subjectCode: 'CSE 104', facultyName: 'Dr. C.S. Raghuvans', facultyCode: 'CSR' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'Basic Mechanical Engineering', subjectCode: 'BME 101', facultyName: 'Dr. Anshul Gangele', facultyCode: 'ASL' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Environmental Studies - I', subjectCode: 'EVS 142', facultyName: 'Dr. Rwitabrata M', facultyCode: 'RWM' },
            { id: 'L4', fromTime: '12:15', toTime: '13:10', subjectName: 'LUNCH', subjectCode: '', facultyName: '', facultyCode: '' },
            { id: 'LUNCH', fromTime: '13:10', toTime: '14:10' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'French - I', subjectCode: 'FLU 144', facultyName: 'Mr. K. Muthuvel', facultyCode: 'KMU' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'Communication Skills - I', subjectCode: 'BCU 141', facultyName: 'Dr. Monika Saxeni', facultyCode: 'MKS' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'Applied Physics - I', subjectCode: 'PHY 101', facultyName: 'Dr. Nirbhay Singh', facultyCode: 'NBS' },
        ],
        Tuesday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Applied Mathematics - I', subjectCode: 'MAT 101', facultyName: 'Dr. Santosh Kr Sharma', facultyCode: 'SNT' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'Applied Physics - I', subjectCode: 'PHY 101', facultyName: 'Dr. Nirbhay Singh', facultyCode: 'NBS' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'LIBRARY/CCA', subjectCode: 'LIBRARY/CCA', facultyName: '', facultyCode: '' },
            { id: 'L4', fromTime: '12:15', toTime: '13:10', subjectName: 'LUNCH', subjectCode: '', facultyName: '', facultyCode: '' },
            { id: 'LUNCH', fromTime: '13:10', toTime: '14:10' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'Basic Civil Engineering Applied Mechanics', subjectCode: 'CIV 101', facultyName: 'Dr. P. Mahakavi', facultyCode: 'PMK' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'Communication Skills - I', subjectCode: 'BCU 141', facultyName: 'Dr. Monika Saxeni', facultyCode: 'MKS' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'LIBRARY/CCA', subjectCode: 'LIBRARY/CCA', facultyName: '', facultyCode: '' },
        ],
        Wednesday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Programming for Problem Solving', subjectCode: 'CSE 104', facultyName: 'Dr. C.S. Raghuvans', facultyCode: 'CSR' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'Workshop/Manufacturing Practices Lab', subjectCode: 'BME 124', facultyName: 'Dr. Susheel Pandey', facultyCode: 'SHP' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Programming for Problem Solving Lab', subjectCode: 'CSE 124', facultyName: 'Dr. C.S. Raghuvans', facultyCode: 'CSR' },
            { id: 'L4', fromTime: '12:15', toTime: '13:10', subjectName: 'LUNCH', subjectCode: '', facultyName: '', facultyCode: '' },
            { id: 'LUNCH', fromTime: '13:10', toTime: '14:10' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'Environmental Studies - I', subjectCode: 'EVS 142', facultyName: 'Dr. Rwitabrata M', facultyCode: 'RWM' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'Applied Mathematics - I', subjectCode: 'MAT 101', facultyName: 'Dr. Santosh Kr Sharma', facultyCode: 'SNT' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'Basic Mechanical Engineering', subjectCode: 'BME 101', facultyName: 'Dr. Anshul Gangele', facultyCode: 'ASL' },
        ],
        Thursday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Applied Physics - I', subjectCode: 'PHY 101', facultyName: 'Dr. Nirbhay Singh', facultyCode: 'NBS' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'Programming for Problem Solving', subjectCode: 'CSE 104', facultyName: 'Dr. C.S. Raghuvans', facultyCode: 'CSR' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Behavioural Science - I', subjectCode: 'BSU 143', facultyName: 'Dr. Yukti', facultyCode: 'YKT' },
            { id: 'L4', fromTime: '12:15', toTime: '13:10', subjectName: 'LUNCH', subjectCode: '', facultyName: '', facultyCode: '' },
            { id: 'LUNCH', fromTime: '13:10', toTime: '14:10' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'Programming for Problem Solving Lab', subjectCode: 'CSE 124', facultyName: 'Dr. C.S. Raghuvans', facultyCode: 'CSR' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'Workshop/Manufacturing Practices Lab', subjectCode: 'BME 124', facultyName: 'Dr. Susheel Pandey', facultyCode: 'SHP' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'Applied Mathematics - I', subjectCode: 'MAT 101', facultyName: 'Dr. Santosh Kr Sharma', facultyCode: 'SNT' },
        ],
        Friday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Applied Physics - I', subjectCode: 'PHY 101', facultyName: 'Dr. Nirbhay Singh', facultyCode: 'NBS' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'Applied Physics Lab - I', subjectCode: 'PHY 121', facultyName: 'Dr. Nirbhay Singh', facultyCode: 'NBS' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'LIBRARY/CCA', subjectCode: 'LIBRARY/CCA', facultyName: '', facultyCode: '' },
            { id: 'L4', fromTime: '12:15', toTime: '13:10', subjectName: 'LUNCH', subjectCode: '', facultyName: '', facultyCode: '' },
            { id: 'LUNCH', fromTime: '13:10', toTime: '14:10' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'Applied Mathematics - I', subjectCode: 'MAT 101', facultyName: 'Dr. Santosh Kr Sharma', facultyCode: 'SNT' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'Basic Mechanical Engineering', subjectCode: 'BME 101', facultyName: 'Dr. Anshul Gangele', facultyCode: 'ASL' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'LIBRARY/CCA', subjectCode: 'LIBRARY/CCA', facultyName: '', facultyCode: '' },
        ],
        Saturday: [],
        Sunday: [],
    },
};

const btechCse1B_Timetable: TimetableData = {
    course: 'B.Tech',
    program: 'CSE',
    semester: '1',
    section: 'B',
    schedule: {
        Monday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Applied Physics - I', subjectCode: 'PHY 101', facultyName: 'Ms. Apoorva Sharma', facultyCode: 'APS' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'PPS LAB / AP LAB - I', subjectCode: 'CSE 124 / PHY 121', facultyName: 'Dr. C.S. Raghuvanshi / Dr. Manisha Singh', facultyCode: 'CSR/MNS' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Basic Mechanical Engineering', subjectCode: 'BME 101', facultyName: 'Dr. Ashish Singh Pare', facultyCode: 'ASP' },
            { id: 'L4', fromTime: '12:15', toTime: '13:10', subjectName: 'LUNCH', subjectCode: '', facultyName: '', facultyCode: '' },
            { id: 'LUNCH', fromTime: '13:10', toTime: '14:10' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'Environmental Studies - I', subjectCode: 'EVS 142', facultyName: 'Dr. Nidhi Shukla', facultyCode: 'NDS' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'Applied Mathematics - I', subjectCode: 'MAT 101', facultyName: 'Dr. Santosh Kr Sharma', facultyCode: 'SNT' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'Programming for Problem Solving', subjectCode: 'CSE 104', facultyName: 'Dr. C.S. Raghuvanshi', facultyCode: 'CSR' },
        ],
        Tuesday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Basic Civil Engineering Applied Mechanics', subjectCode: 'CIV 101', facultyName: 'Mr. Sachin Tiwari', facultyCode: 'SCH' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'Applied Physics Lab - I', subjectCode: 'PHY 121', facultyName: 'Dr. Manisha Singh', facultyCode: 'MNS' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'LIBRARY/CCA', subjectCode: '', facultyName: '', facultyCode: '' },
            { id: 'L4', fromTime: '12:15', toTime: '13:10', subjectName: 'LUNCH', subjectCode: '', facultyName: '', facultyCode: '' },
            { id: 'LUNCH', fromTime: '13:10', toTime: '14:10' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'Basic Mechanical Engineering', subjectCode: 'BME 101', facultyName: 'Dr. Ashish Singh Pare', facultyCode: 'ASP' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'French - I', subjectCode: 'FLU 144', facultyName: 'Dr. Neelam Singh Ton', facultyCode: 'NLT' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'Communication Skills - I', subjectCode: 'BCU 141', facultyName: 'Dr. Monika Saxena', facultyCode: 'MKS' },
        ],
        Wednesday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Applied Mathematics - I', subjectCode: 'MAT 101', facultyName: 'Dr. Santosh Kr Sharma', facultyCode: 'SNT' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'LIBRARY/CCA', subjectCode: '', facultyName: '', facultyCode: '' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Applied Physics - I', subjectCode: 'PHY 101', facultyName: 'Dr. Pankaj Mishra', facultyCode: 'PKM' },
            { id: 'L4', fromTime: '12:15', toTime: '13:10', subjectName: 'LUNCH', subjectCode: '', facultyName: '', facultyCode: '' },
            { id: 'LUNCH', fromTime: '13:10', toTime: '14:10' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'WP LAB / PPS LAB', subjectCode: 'BME 124 / CSE 124', facultyName: 'Dr. Ashish Singh Pare / Dr. C.S. Raghuvanshi', facultyCode: 'ASP/CSR' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'LIBRARY/CCA', subjectCode: '', facultyName: '', facultyCode: '' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'LIBRARY/CCA', subjectCode: '', facultyName: '', facultyCode: '' },
        ],
        Thursday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Programming for Problem Solving', subjectCode: 'CSE 104', facultyName: 'Dr. C.S. Raghuvanshi', facultyCode: 'CSR' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'Applied Mathematics - I', subjectCode: 'MAT 101', facultyName: 'Dr. Santosh Kr Sharma', facultyCode: 'SNT' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Behavioural Science - I', subjectCode: 'BSU 143', facultyName: 'Dr. Shubhagata Awasi', facultyCode: 'SBA' },
            { id: 'L4', fromTime: '12:15', toTime: '13:10', subjectName: 'LUNCH', subjectCode: '', facultyName: '', facultyCode: '' },
            { id: 'LUNCH', fromTime: '13:10', toTime: '14:10' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'LIBRARY/CCA', subjectCode: '', facultyName: '', facultyCode: '' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'Applied Physics - I', subjectCode: 'PHY 101', facultyName: 'Dr. Pankaj Mishra', facultyCode: 'PKM' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'Environmental Studies - I', subjectCode: 'EVS 142', facultyName: 'Dr. Nidhi Shukla', facultyCode: 'NDS' },
        ],
        Friday: [
            { id: 'L1', fromTime: '09:15', toTime: '10:10', subjectName: 'Programming for Problem Solving', subjectCode: 'CSE 104', facultyName: 'Dr. C.S. Raghuvanshi', facultyCode: 'CSR' },
            { id: 'L2', fromTime: '10:15', toTime: '11:10', subjectName: 'Applied Mathematics - I', subjectCode: 'MAT 101', facultyName: 'Dr. Santosh Kr Sharma', facultyCode: 'SNT' },
            { id: 'L3', fromTime: '11:15', toTime: '12:10', subjectName: 'Basic Civil Engineering Applied Mechanics', subjectCode: 'CIV 101', facultyName: 'Mr. Sachin Tiwari', facultyCode: 'SCH' },
            { id: 'L4', fromTime: '12:15', toTime: '13:10', subjectName: 'LUNCH', subjectCode: '', facultyName: '', facultyCode: '' },
            { id: 'LUNCH', fromTime: '13:10', toTime: '14:10' },
            { id: 'L5', fromTime: '14:15', toTime: '15:10', subjectName: 'Basic Mechanical Engineering', subjectCode: 'BME 101', facultyName: 'Dr. Ashish Singh Pare', facultyCode: 'ASP' },
            { id: 'L6', fromTime: '15:15', toTime: '16:10', subjectName: 'Applied Physics - I', subjectCode: 'PHY 101', facultyName: 'Dr. Pankaj Mishra', facultyCode: 'PKM' },
            { id: 'L7', fromTime: '16:15', toTime: '17:10', subjectName: 'LIBRARY/CCA', subjectCode: '', facultyName: '', facultyCode: '' },
        ],
        Saturday: [],
        Sunday: [],
    },
};

export const defaultTimetables: Record<string, TimetableData> = {
    'B.Tech-CSE-1-A': btechCse1A_Timetable,
    'B.Tech-CSE-1-B': btechCse1B_Timetable,
};
